### ISSUE TITLE
File extension

### ISSUE THREAD

**Issue by dol** [releng-tool/releng-tool#1]
I really like the tool. I played with the example repo and it's very neat.
The only thing that I would change is to add a file extension to the configuration files. E.g nghttp2.releng instead of nghttp2. https://github.com/releng-tool/releng-tool-examples/blob/master/nghttp2/package/nghttp2/nghttp2

With an file extension it's possible to filter the corresponding files for linting or syntax highlighting. A not so good example are the Dockerfiles with no extension. An editor needs to understand, that a 'Dockerfile' needs the highlighting of a Dockerfile. If you change the name, you need to adopt your editor/scan/filter scripts.
On a OS level I'd like to open an extension with an certain application. Without an extension this might be difficult.

**Comment by jdknight** [comment]
@dol, I am a bit selfishly fond of the more minimalistic filenames. Usually the environments I work in have a text editor default-open non-extension files; along with the editors able to detect the shebang line to know its a Python-based scripts (for highlighting benefits). That being said, not all environment are like this, so I have no problem being a bit more flexible in providing extensions for these files.

What about the following solution:

1. By default, releng-tool looks for file assets in the same manner it does right now.
2. If a package asset cannot be found, releng-tool looks for an alternative file with a `.releng` extension.

For the [nghttp2](https://github.com/releng-tool/releng-tool-examples/tree/master/nghttp2) example being referenced, this means a developer could define the following alternative files and achieve the same results:

```
package/libcares/libcares.releng
package/libev/libev.releng
package/libjemalloc/libjemalloc.releng
package/libnghttp2/libnghttp2.releng
package/libopenssl/libopenssl.releng
package/libopenssl/libopenssl-build.releng
package/libopenssl/libopenssl-configure.releng
package/libopenssl/libopenssl-install.releng
package/libxml2/libxml2.releng
package/libzlib/libzlib.releng
package/libzlib/libzlib-build.releng
package/libzlib/libzlib-configure.releng
package/libzlib/libzlib-install.releng
package/nghttp2/nghttp2.releng
```

Another point to consider is that these files are Python-based scripts. Instead of introducing a new `releng` extension, it may be easier to leave the extension to be `py`. This prevents the need for a user to configure a new extension type when they may have `py` already registered -- counter-point is that `py` may be registered for execution, and since these scripts are not designed to be directly execution, `releng` may be a better fit.

Lastly, thinking about a good alternative name for the root configuration file `releng` (as well as `releng-overrides` and `releng-post`). Originally, this file was named `releng.py`; however, this project specifically moved away from that name to prevent namespacing issues (see acb414dba5bc41fdbd052e096b7a95882b3bc6fd). Maybe `conf.releng` would be a good alternative name as well -- and if (in the previous point), the `py` extension is preferred, `conf.py` may be "better".

Currently, if an alternative extension pattern is preferred, I am currently leaning towards the `.releng` pattern for packages and no alternative name for `releng` root configuration scripts.

**Comment by dol** [comment]
I understand your points. It's your project and your working ground. I only wanted to challange this point. You did a very good job to elaborate your opinion in a clear and reasonable manner. Thank you for your thoughts and opinion on this.
